#!/usr/bin/env node
/**
 * Editor latency harness (LOA-90, §5.9). Runs the shipped extension stack in
 * a real Chromium against a deterministic 10k-word document and gates the
 * per-keystroke p95 against an absolute SLO and a committed baseline — the
 * same contract `loam-bench switcher` uses for the omnibar.
 *
 * What is measured: one character inserted mid-document, the resulting CM6
 * transaction, the synchronous DOM write, and the layout it forces. Browser
 * paint and vsync sit outside that number; everything the editor does is
 * inside it.
 *
 * Usage:
 *   node scripts/editor-bench.mjs                  # run and print the report
 *   node scripts/editor-bench.mjs --check          # enforce SLO + regression gates
 *   node scripts/editor-bench.mjs --write-baseline # refresh the baseline
 *   node scripts/editor-bench.mjs --write-doc      # refresh docs/editor-perf.md
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createServer } from "node:http";
import { dirname, extname, join, resolve } from "node:path";
import { chromium } from "playwright";

const root = resolve(new URL("..", import.meta.url).pathname);
const distDir = join(root, "apps/desktop/dist");
const baselinePath = join(root, "apps/desktop/baselines/editor.json");
const docPath = join(root, "docs/editor-perf.md");

/** §5.9: typing stays under one 60 Hz frame in a 10k-word document. */
const KEYSTROKE_P95_SLO_MS = 16;
/** A run slower than baseline × 1.10 is a regression (matches loam-bench). */
const REGRESSION_FACTOR = 1.1;
/**
 * AC3 (LOA-119): decoration is viewport-only, so a 20x longer document must
 * not cost 20x per keystroke. Some growth is real — the parser and the
 * document tree are bigger — so the gate allows a factor, not equality.
 */
const SCALING_FACTOR = 3;

/**
 * Below this the regression band is pure timer noise: Chromium clamps
 * `performance.now()` to 100 µs, so a sub-millisecond p95 moves a whole tick
 * at a time. The absolute SLO still applies at every value.
 */
const REGRESSION_FLOOR_MS = 2;

const MIME = {
  ".html": "text/html",
  ".js": "text/javascript",
  ".mjs": "text/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".woff2": "font/woff2",
  ".svg": "image/svg+xml",
  ".png": "image/png",
};

function serve(dir) {
  const server = createServer((request, response) => {
    const path = decodeURIComponent(new URL(request.url, "http://localhost").pathname);
    let file = join(dir, path === "/" ? "index.html" : path);
    if (!existsSync(file)) file = join(dir, "index.html");
    try {
      const body = readFileSync(file);
      response.writeHead(200, {
        "content-type": MIME[extname(file)] ?? "application/octet-stream",
      });
      response.end(body);
    } catch {
      response.writeHead(404);
      response.end();
    }
  });
  return new Promise((ready) => {
    server.listen(0, "127.0.0.1", () => ready({ server, port: server.address().port }));
  });
}

function ensureBuild() {
  if (existsSync(join(distDir, "index.html"))) return;
  execFileSync("pnpm", ["--filter", "@loam-app/desktop", "build"], { cwd: root, stdio: "inherit" });
}

async function run() {
  ensureBuild();
  const { server, port } = await serve(distDir);
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
    await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: "networkidle", timeout: 60_000 });
    await page.waitForFunction(() => "__LOAM_BENCH__" in window, null, { timeout: 30_000 });
    const typing = await page.evaluate(() => window.__LOAM_BENCH__.benchTyping());
    const layers = await page.evaluate(() => window.__LOAM_BENCH__.benchLayers());
    const scaling = await page.evaluate(() => window.__LOAM_BENCH__.benchScaling());
    const words = await page.evaluate(
      () => window.__LOAM_BENCH__.benchDocument().split(/\s+/).filter(Boolean).length,
    );
    return { words, typing, layers, scaling };
  } finally {
    await browser.close();
    server.close();
  }
}

function readBaseline() {
  try {
    return JSON.parse(readFileSync(baselinePath, "utf8"));
  } catch {
    return null;
  }
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function renderDoc(report) {
  const scalingRows = (report.scaling ?? [])
    .map(
      (point) =>
        `| ${point.words.toLocaleString("en-US")} | ${point.meanMs.toFixed(3)} | ${point.p95Ms.toFixed(3)} |`,
    )
    .join("\n");
  const rows = report.layers
    .map(
      (layer) =>
        `| \`${layer.layer}\` | ${layer.description} | ${layer.cumulativeMeanMs.toFixed(3)} | ${layer.marginalMeanMs.toFixed(3)} | ${layer.cumulativeP95Ms.toFixed(3)} |`,
    )
    .join("\n");
  return `# Editor performance (§5.9)

Generated by \`node scripts/editor-bench.mjs --write-doc\`. Numbers come from a
headless Chromium running the shipped extension stack, so they move with the
machine — the CI gate is the absolute SLO plus a ±10 % band around
\`apps/desktop/baselines/editor.json\`, not these exact values.

**Measured**: one character inserted mid-document, the CM6 transaction it
produces, the synchronous DOM write, and the layout it forces. Browser paint
and vsync are outside the number.

## Keystroke latency — ${report.words.toLocaleString("en-US")}-word document

| Metric | ms |
| --- | --- |
| mean | ${report.typing.meanMs.toFixed(3)} |
| p50 | ${report.typing.p50Ms.toFixed(3)} |
| p95 | ${report.typing.p95Ms.toFixed(3)} |
| max | ${report.typing.maxMs.toFixed(3)} |
| samples | ${report.typing.samples} |

Budget: **p95 ≤ ${KEYSTROKE_P95_SLO_MS} ms** (one 60 Hz frame).

## Edit cost by document size

A local edit is viewport work, so it should stay flat as the note grows. CI
fails if the largest note costs more than ${SCALING_FACTOR}x the smallest.

| Words | Mean (ms) | p95 (ms) |
| --- | --- | --- |
${scalingRows}

## Per-extension dispatch cost

Each row adds one layer of \`extensionLayers()\` on top of the row above, so
"marginal" is what that layer costs per keystroke. Means, not p95s: Chromium
clamps \`performance.now()\` to 100 µs and most layers cost less than one tick,
so anything within noise of zero reads as ~0.000.

| Layer | Contents | Cumulative mean (ms) | Marginal mean (ms) | Cumulative p95 (ms) |
| --- | --- | --- | --- | --- |
${rows}
`;
}

const args = process.argv.slice(2);
const report = await run();
console.log(JSON.stringify(report, null, 2));

if (args.includes("--write-baseline")) {
  writeJson(baselinePath, { words: report.words, typing: report.typing });
  console.error(`baseline written to ${baselinePath}`);
}

if (args.includes("--write-doc")) {
  mkdirSync(dirname(docPath), { recursive: true });
  writeFileSync(docPath, renderDoc(report));
  console.error(`profile written to ${docPath}`);
}

if (args.includes("--check")) {
  const failures = [];
  const measured = report.typing.p95Ms;
  if (measured > KEYSTROKE_P95_SLO_MS) {
    failures.push(
      `keystroke p95: ${measured.toFixed(2)} ms exceeds SLO ${KEYSTROKE_P95_SLO_MS.toFixed(2)} ms`,
    );
  }
  const points = report.scaling ?? [];
  const smallest = points[0];
  const largest = points.at(-1);
  if (smallest && largest && smallest.meanMs > 0) {
    const growth = largest.meanMs / smallest.meanMs;
    if (growth > SCALING_FACTOR) {
      failures.push(
        `edit cost scales with document size: ${largest.words} words costs ${growth.toFixed(2)}x ` +
          `the ${smallest.words}-word note (limit ${SCALING_FACTOR}x)`,
      );
    }
  }

  const baseline = readBaseline();
  if (baseline?.typing?.p95Ms && measured > REGRESSION_FLOOR_MS) {
    const ceiling = baseline.typing.p95Ms * REGRESSION_FACTOR;
    if (measured > ceiling) {
      failures.push(
        `keystroke p95: ${measured.toFixed(2)} ms regresses >10% over baseline ${baseline.typing.p95Ms.toFixed(2)} ms`,
      );
    }
  }
  if (failures.length > 0) {
    for (const failure of failures) console.error(`FAIL ${failure}`);
    process.exit(1);
  }
  console.error("editor perf gates passed");
}
